/* The following code was generated by JFlex 1.7.0-SNAPSHOT tweaked for IntelliJ platform */

package org.argus.cit.intellij.core.lang.lexer;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static org.argus.cit.intellij.core.lang.psi.JawaTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0-SNAPSHOT
 * from the specification file <tt>_JawaLexer.flex</tt>
 */
public class _JawaLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [12, 6, 3]
   * Total runtime size is 16672 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>9]<<6)|((ch>>3)&0x3f)]<<3)|(ch&0x7)];
  }

  /* The ZZ_CMAP_Z table has 2176 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1"+
    "\20\1\21\1\22\3\21\1\23\1\24\1\25\1\21\14\26\1\27\50\26\1\30\2\26\1\31\1\32"+
    "\1\33\1\34\25\26\1\35\20\21\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1"+
    "\47\1\50\1\21\1\51\1\52\1\53\1\54\1\55\1\56\2\21\1\26\1\57\1\60\5\21\2\26"+
    "\1\61\7\21\1\26\1\62\20\21\1\26\1\63\1\21\1\64\40\21\1\65\5\21\1\66\11\21"+
    "\1\67\1\70\1\71\1\72\1\21\1\73\6\21\1\74\2\21\1\75\1\76\7\21\123\26\1\77\7"+
    "\26\1\100\1\101\12\26\1\102\24\21\1\26\1\103\u0582\21\1\104\u017f\21");

  /* The ZZ_CMAP_Y table has 4416 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\2\0\1\2\1\3\1\4\1\5\1\6\2\7\1\10\1\11\1\12\1\13\1\14\1\15\4\0\1\16"+
    "\1\17\1\16\2\7\1\20\3\7\1\20\71\7\1\21\1\7\1\22\1\0\1\23\1\24\2\0\16\25\1"+
    "\26\1\27\1\30\1\31\2\7\1\32\11\7\1\33\21\7\1\34\1\35\24\7\1\36\3\7\1\20\1"+
    "\37\1\36\4\7\1\0\1\40\4\25\1\41\1\42\1\0\3\7\2\43\3\0\1\25\1\44\5\7\1\45\3"+
    "\25\1\46\1\47\13\7\1\50\1\51\1\52\1\53\1\25\1\54\2\0\1\55\3\7\3\25\1\56\12"+
    "\7\1\57\1\25\1\60\1\0\1\25\1\35\3\7\1\45\1\61\1\16\2\7\1\57\1\62\1\63\1\64"+
    "\2\0\3\7\1\65\10\0\2\7\1\23\5\0\1\66\3\25\1\67\6\7\1\70\2\25\1\71\1\7\1\72"+
    "\1\25\1\36\1\7\1\73\1\74\1\75\2\7\1\76\1\77\1\100\1\51\1\101\1\102\1\103\1"+
    "\72\1\25\1\22\1\0\1\104\1\105\1\75\2\7\1\76\1\106\1\107\1\110\1\111\1\112"+
    "\1\113\1\114\1\25\1\115\1\0\1\104\1\33\1\32\2\7\1\76\1\116\1\100\1\41\1\117"+
    "\1\120\1\0\1\72\1\25\1\0\1\37\1\104\1\74\1\75\2\7\1\76\1\116\1\100\1\51\1"+
    "\111\1\114\1\103\1\72\1\25\1\37\1\0\1\121\1\122\1\123\1\124\1\125\1\122\1"+
    "\7\1\126\1\127\1\130\1\131\1\0\1\114\1\25\2\0\1\132\1\26\1\76\2\7\1\76\1\7"+
    "\1\133\1\134\1\130\1\135\1\43\1\72\1\25\2\0\1\104\1\26\1\76\2\7\1\76\1\136"+
    "\1\100\1\134\1\130\1\135\1\30\1\72\1\25\1\137\1\0\1\104\1\26\1\76\4\7\1\140"+
    "\1\134\1\141\1\102\1\142\1\72\1\25\1\0\1\143\1\144\1\7\1\20\1\143\2\7\1\32"+
    "\1\145\1\20\1\146\1\147\1\25\1\114\1\25\1\150\1\0\1\36\5\7\1\151\1\44\1\152"+
    "\1\153\1\25\1\154\4\0\1\155\1\156\1\157\1\36\1\160\1\161\1\151\1\162\1\163"+
    "\1\164\1\25\1\165\4\0\1\120\2\0\1\154\1\25\1\154\1\166\1\167\1\7\1\36\3\7"+
    "\1\23\1\40\1\25\1\134\1\170\1\25\1\40\3\25\1\171\1\172\7\0\5\7\1\45\1\25\1"+
    "\173\1\25\1\154\1\57\1\174\1\175\1\176\1\177\1\7\1\200\1\201\1\25\1\164\4"+
    "\7\1\33\1\17\5\7\1\202\51\7\1\123\1\20\1\123\5\7\1\123\4\7\1\123\1\20\1\123"+
    "\1\7\1\20\7\7\1\123\10\7\1\203\4\0\2\7\2\0\12\7\2\204\1\36\114\7\1\74\2\7"+
    "\1\36\2\7\1\43\11\7\1\205\1\47\1\120\1\7\1\26\1\206\1\0\2\7\1\206\1\0\2\7"+
    "\1\207\1\0\1\7\1\26\1\210\1\0\6\7\1\211\3\25\1\212\1\213\1\25\1\154\3\0\1"+
    "\214\1\25\1\154\13\7\1\0\5\7\1\215\10\7\1\204\1\0\3\7\1\20\1\25\1\216\1\25"+
    "\1\216\1\114\1\25\3\7\1\204\1\23\1\0\5\7\1\217\3\7\1\22\1\25\1\154\4\0\2\7"+
    "\1\152\1\216\6\7\1\170\1\153\3\25\1\51\1\25\1\154\1\25\1\154\1\142\1\0\1\25"+
    "\1\153\10\0\1\220\5\7\1\211\1\25\1\220\1\217\1\25\1\154\1\0\1\66\1\216\1\0"+
    "\1\221\3\7\1\71\1\176\1\25\1\35\4\7\1\57\1\25\1\216\1\0\4\7\1\211\2\25\1\0"+
    "\1\25\1\222\1\25\1\35\3\7\1\204\12\0\1\223\2\25\1\224\1\225\1\154\30\7\6\25"+
    "\1\164\1\226\42\7\2\204\4\7\2\204\1\7\1\227\3\7\1\204\6\7\1\26\1\163\1\230"+
    "\1\23\1\231\1\217\1\7\1\23\1\230\1\23\5\0\1\232\1\0\1\102\1\233\1\0\1\234"+
    "\3\0\1\37\1\142\2\0\1\7\1\23\6\0\4\25\1\233\1\0\1\235\1\143\1\145\1\236\1"+
    "\24\1\237\1\7\1\240\1\241\1\242\2\0\4\25\1\243\1\233\144\0\1\114\6\25\1\154"+
    "\42\0\5\7\1\20\5\7\1\20\20\7\1\23\1\244\1\245\1\0\4\7\1\33\1\17\7\7\1\142"+
    "\1\0\1\102\2\7\1\20\1\0\10\20\4\25\5\0\1\142\72\0\1\246\3\0\1\40\1\25\1\236"+
    "\1\247\1\36\11\7\1\20\1\250\1\36\12\7\1\202\1\241\4\7\1\204\1\36\12\7\1\20"+
    "\2\0\3\7\1\43\6\0\170\7\1\204\11\0\72\7\1\204\5\0\21\7\1\23\10\0\5\7\1\204"+
    "\41\7\1\23\2\7\1\25\1\245\2\0\5\7\1\152\1\223\1\251\3\7\1\57\10\7\1\57\1\25"+
    "\1\154\3\0\1\142\1\7\1\143\14\7\1\75\3\7\1\204\1\7\7\0\1\142\1\7\1\252\1\253"+
    "\2\7\1\45\3\0\6\7\1\217\1\0\1\35\5\7\1\211\1\25\1\171\1\0\1\25\1\154\2\25"+
    "\1\35\1\254\1\25\1\35\2\7\1\57\1\164\2\7\1\152\1\25\1\216\1\0\3\7\1\23\1\67"+
    "\5\7\1\45\1\25\1\233\1\142\1\25\1\154\1\255\1\7\1\25\1\256\5\7\1\71\1\153"+
    "\1\0\1\253\1\257\1\25\1\154\2\7\1\20\1\260\6\7\1\175\1\261\1\215\2\0\1\262"+
    "\1\7\1\45\1\263\1\0\3\264\1\0\2\20\5\7\1\202\1\204\1\0\16\7\1\45\1\265\1\25"+
    "\1\154\64\7\1\217\1\0\2\7\1\20\1\266\5\7\1\217\40\0\55\7\1\204\15\7\1\22\4"+
    "\0\1\20\1\0\1\266\1\267\1\7\1\76\1\20\1\163\1\270\15\7\1\22\3\0\1\266\54\7"+
    "\1\204\2\0\10\7\1\143\6\7\5\0\1\7\1\217\2\25\2\0\2\25\1\271\2\0\1\272\4\0"+
    "\1\26\20\7\1\23\2\0\1\25\1\154\1\36\2\7\1\273\1\36\2\7\1\43\1\274\12\7\1\20"+
    "\3\143\1\275\4\0\1\7\1\136\2\7\1\20\2\7\1\276\1\7\1\204\1\7\1\204\4\0\17\7"+
    "\1\43\10\0\6\25\1\171\20\0\1\277\20\0\3\7\1\23\6\7\1\120\1\0\1\233\3\0\4\7"+
    "\2\0\2\7\1\55\1\300\4\7\1\57\1\44\3\7\1\204\4\7\1\217\1\7\1\301\5\0\23\7\1"+
    "\204\1\25\1\154\12\0\5\7\1\0\6\7\1\217\23\0\46\7\1\20\1\0\2\7\1\204\1\0\1"+
    "\7\23\0\1\204\1\76\4\7\1\33\1\302\2\7\1\204\1\0\2\7\1\20\1\0\3\7\1\20\10\0"+
    "\2\7\1\303\1\0\2\7\1\204\1\0\3\7\1\22\10\0\7\7\1\274\10\0\1\304\1\226\1\136"+
    "\1\36\2\7\1\217\1\110\4\0\3\7\1\23\3\7\1\23\4\0\1\7\1\36\2\7\1\305\3\0\6\7"+
    "\1\204\1\0\2\7\1\204\1\0\2\7\1\43\1\0\2\7\1\22\15\0\11\7\1\120\6\0\6\7\1\43"+
    "\1\0\6\7\1\43\41\0\1\221\6\7\1\25\1\153\3\0\1\114\1\25\1\0\1\102\1\221\5\7"+
    "\1\25\1\44\2\0\3\7\1\120\1\25\1\154\1\221\3\7\1\152\1\25\1\134\1\25\2\0\4"+
    "\7\1\306\1\0\1\221\5\7\1\45\1\25\1\307\1\310\1\25\1\311\4\0\2\7\1\32\2\7\1"+
    "\211\1\25\11\0\1\20\1\237\1\7\1\33\1\7\1\120\5\7\1\152\1\25\1\44\1\25\1\154"+
    "\1\132\1\74\1\75\2\7\1\76\1\116\1\100\1\51\1\111\1\131\1\241\1\72\2\171\41"+
    "\0\6\7\2\25\1\312\1\0\1\25\1\154\24\0\5\7\1\152\1\164\1\25\1\233\2\0\1\257"+
    "\4\0\6\7\2\25\1\313\1\0\1\25\1\154\4\0\5\7\1\45\1\25\1\0\1\25\1\154\6\0\3"+
    "\7\1\314\1\25\1\216\1\25\1\154\54\0\10\7\1\25\1\154\1\0\1\142\70\0\7\7\1\120"+
    "\40\0\63\7\1\22\14\0\15\25\1\153\2\0\30\7\1\217\27\0\5\7\1\20\72\0\10\7\1"+
    "\20\67\0\7\7\1\120\3\7\1\20\1\25\1\154\14\0\3\7\1\204\1\171\1\0\6\7\1\153"+
    "\1\0\1\217\1\0\1\25\1\154\1\266\2\7\1\241\2\7\56\0\10\7\1\23\1\0\1\71\4\25"+
    "\1\153\1\0\1\102\1\221\1\7\14\0\1\22\77\0\15\7\1\43\1\7\1\23\1\7\1\120\1\7"+
    "\1\315\130\0\1\272\1\316\1\44\1\66\1\317\1\216\3\0\1\320\22\0\1\310\67\0\12"+
    "\7\1\26\10\7\1\26\1\321\1\322\1\7\1\323\1\136\7\7\1\33\1\324\2\26\3\7\1\325"+
    "\1\163\1\143\1\76\51\7\1\204\3\7\1\76\2\7\1\202\3\7\1\202\2\7\1\26\3\7\1\26"+
    "\2\7\1\20\3\7\1\20\3\7\1\76\3\7\1\76\2\7\1\202\1\326\14\25\1\153\1\66\5\25"+
    "\1\171\1\277\1\0\1\234\2\0\1\66\1\40\1\25\52\0\30\7\1\23\1\0\1\153\45\0\1"+
    "\136\3\7\1\155\1\36\1\202\1\327\1\235\1\330\1\155\1\227\1\155\2\202\1\113"+
    "\1\7\1\32\1\7\1\217\1\331\1\32\1\7\1\217\116\0\3\25\1\154\3\25\1\154\3\25"+
    "\1\154\16\0\32\7\1\20\5\0\106\7\1\23\1\0\33\7\1\204\120\7\1\22\53\0\3\7\1"+
    "\204\134\0\36\25\2\0");

  /* The ZZ_CMAP_A table has 1744 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\2\1\1\1\13\1\14\1\1\2\0\1\2\1\0\1\15\1\26\1\4\1\67\1\70\1\11\1\33"+
    "\1\34\1\66\1\64\1\20\1\65\1\10\1\16\12\7\1\23\1\17\1\72\1\24\1\25\1\0\1\6"+
    "\3\3\1\63\1\61\15\3\1\31\1\12\1\32\1\21\1\4\1\5\1\51\1\50\1\37\1\41\1\36\1"+
    "\57\1\46\1\54\1\56\2\3\1\47\1\60\1\44\1\40\1\52\1\3\1\35\1\45\1\43\1\53\1"+
    "\3\1\55\1\42\1\62\1\3\1\27\1\22\1\30\1\71\6\0\1\13\4\0\1\3\12\0\1\3\2\0\7"+
    "\3\1\0\2\3\4\0\4\3\6\0\5\3\7\0\1\3\1\0\1\3\1\0\10\4\5\3\1\0\2\3\2\0\4\3\1"+
    "\0\1\3\6\0\1\3\1\0\3\3\1\0\1\3\1\0\4\3\1\0\13\3\1\0\3\3\1\0\7\4\6\3\1\0\7"+
    "\3\1\0\1\3\7\0\15\4\1\0\1\4\1\0\2\4\1\0\2\4\1\0\1\4\3\3\5\0\3\4\5\0\3\3\7"+
    "\4\4\0\2\3\1\4\13\3\1\0\1\3\7\4\2\0\6\4\2\3\2\4\1\0\4\4\2\3\2\4\3\3\2\0\2"+
    "\3\1\4\6\3\3\4\2\0\11\3\3\4\1\3\6\0\4\4\2\3\2\0\2\4\1\3\11\4\1\3\3\4\1\3\5"+
    "\4\2\0\1\3\3\4\7\0\11\4\6\3\3\4\1\3\2\4\1\3\7\4\2\3\2\4\2\0\2\4\1\3\3\4\1"+
    "\0\10\3\2\0\2\3\2\0\6\3\1\0\7\3\1\0\1\3\3\0\4\3\2\0\1\4\1\3\3\4\2\0\3\4\1"+
    "\3\10\0\1\4\4\0\2\3\1\0\1\3\1\0\3\4\1\0\6\3\4\0\2\3\1\0\2\3\1\0\2\3\1\0\2"+
    "\3\2\0\1\4\1\0\5\4\4\0\2\4\2\0\3\4\3\0\1\4\7\0\4\3\1\0\1\3\7\0\4\4\3\3\1\4"+
    "\2\0\1\3\1\0\2\3\1\0\3\3\2\4\1\0\3\4\2\0\1\3\11\0\1\4\1\3\1\0\6\3\3\0\3\3"+
    "\1\0\4\3\3\0\2\3\1\0\1\3\1\0\2\3\3\0\2\3\3\0\2\3\4\0\5\4\3\0\3\4\1\0\4\4\2"+
    "\0\1\3\6\0\5\4\1\0\5\3\3\0\1\3\7\4\1\0\2\4\5\0\2\4\1\0\4\3\1\0\3\3\1\0\2\3"+
    "\5\0\3\3\2\0\1\3\3\4\1\0\4\4\1\3\10\0\1\3\2\0\6\3\2\0\2\4\1\0\7\3\1\0\1\3"+
    "\4\0\1\4\4\0\6\4\1\0\1\4\3\0\2\4\4\0\1\3\1\4\2\3\4\4\7\3\10\4\1\0\2\4\7\0"+
    "\2\3\1\0\1\3\2\0\2\3\1\0\1\3\2\0\1\3\6\0\4\3\1\0\3\3\1\0\1\3\1\0\1\3\2\0\2"+
    "\3\1\0\3\3\2\4\1\0\2\4\1\3\2\0\5\3\1\0\1\3\1\0\6\4\2\0\2\4\2\0\4\3\5\0\1\4"+
    "\1\0\1\4\1\0\1\4\4\0\2\4\5\3\10\4\11\0\1\4\1\0\7\4\1\3\2\4\4\3\3\4\1\3\3\4"+
    "\2\3\7\4\3\3\4\4\5\3\14\4\1\3\1\4\3\3\1\0\7\3\2\0\3\4\6\3\2\0\3\3\3\0\2\4"+
    "\2\3\3\4\3\0\2\3\2\4\4\0\1\3\1\0\2\4\4\0\4\3\10\4\3\0\1\3\4\0\1\3\1\4\5\0"+
    "\3\4\2\0\1\3\1\4\1\3\5\0\4\4\4\0\4\3\4\0\5\4\3\3\3\4\5\3\2\4\3\0\3\3\3\4\1"+
    "\0\5\4\4\3\1\4\4\3\3\4\2\3\5\0\4\4\1\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3\2\0\3\3"+
    "\1\0\6\3\2\0\2\3\2\13\6\0\1\4\13\0\1\4\5\0\1\3\4\0\1\3\1\0\5\3\2\0\1\3\1\0"+
    "\4\3\1\0\3\3\2\0\4\3\5\0\5\3\4\0\1\3\1\0\3\4\2\3\3\4\3\0\4\3\3\4\2\3\11\0"+
    "\2\3\4\4\2\3\4\0\2\4\2\0\3\3\6\4\1\0\3\3\1\4\3\3\1\4\4\3\1\4\4\3\3\0\1\3\1"+
    "\0\1\3\2\0\5\3\1\4\2\3\2\4\5\3\1\0\4\3\2\4\4\0\1\3\3\4\2\3\1\4\5\3\2\4\3\0"+
    "\3\3\4\0\3\3\2\4\2\0\6\3\1\0\3\4\1\0\2\4\5\0\5\3\5\0\1\3\1\4\3\3\1\0\2\3\1"+
    "\0\2\3\3\0\2\4\10\0\3\4\3\3\4\0\1\4\6\0\2\3\2\0\3\3\3\0\3\3\1\0\2\3\1\0\1"+
    "\3\5\0\1\4\2\0\2\3\1\4\6\0\5\4\2\0\1\3\3\0\1\3\2\0\4\3\1\0\2\3\2\0\1\3\3\4"+
    "\1\0\2\4\1\0\5\3\2\4\1\0\3\3\1\4\2\0\1\3\1\0\1\4\4\3\5\0\3\4\3\0\2\4\1\3\1"+
    "\0\1\3\3\0\4\4\2\3\1\0\1\3\1\4\3\0\1\3\3\0\2\3\3\0\3\4\2\3\3\0\2\4\1\0\2\4"+
    "\3\0\6\4\2\0\3\4\2\0\4\4\4\0\1\3\2\0\2\3\2\0\4\3\1\0\4\3\1\0\1\3\1\0\6\3\2"+
    "\0\5\3\1\0\4\3\1\0\4\3\2\0\2\4\1\0\1\3\1\0\1\3\5\0\1\3\1\0\1\3\1\0\3\3\1\0"+
    "\3\3\1\0\3\3");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\2\1\1\7\1\10\1\11\1\12\1\13\2\1\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\16\3\1\23"+
    "\1\24\1\25\1\1\2\0\1\26\4\0\1\5\1\27"+
    "\1\0\1\30\3\0\1\31\1\0\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\20\3\1\41\3\3\1\42"+
    "\1\43\7\0\1\44\12\3\1\45\13\3\1\43\6\0"+
    "\1\46\1\0\3\3\1\47\2\3\1\50\2\3\1\51"+
    "\1\52\1\3\1\53\2\3\1\54\5\3\1\0\1\55"+
    "\2\0\1\56\1\0\1\57\4\3\1\60\1\61\1\62"+
    "\1\63\5\3\1\64\1\65\2\3\1\0\1\66\1\0"+
    "\1\67\1\70\2\3\1\71\1\72\1\73\4\3\2\0"+
    "\1\74\5\3\2\0\5\3\2\0\1\3\1\75\3\3"+
    "\1\76\1\0\1\77\1\100\1\101\2\3\1\0\1\102"+
    "\1\3\1\0\1\103\3\0\1\104";

  private static int [] zzUnpackAction() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0162\0\u019d"+
    "\0\u01d8\0\u0213\0\u024e\0\73\0\73\0\u0289\0\73\0\u02c4"+
    "\0\u02ff\0\73\0\73\0\73\0\73\0\73\0\73\0\73"+
    "\0\u033a\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7"+
    "\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639\0\73\0\73"+
    "\0\73\0\u0674\0\u06af\0\u06ea\0\73\0\u0725\0\u0760\0\u079b"+
    "\0\u07d6\0\u0811\0\73\0\u01d8\0\73\0\u084c\0\u0213\0\u0887"+
    "\0\u08c2\0\u08fd\0\73\0\u0938\0\73\0\73\0\73\0\73"+
    "\0\73\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5"+
    "\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37\0\u0c72\0\u0cad"+
    "\0\u0ce8\0\261\0\u0d23\0\u0d5e\0\u0d99\0\73\0\73\0\u0dd4"+
    "\0\u0e0f\0\u0e4a\0\u0e85\0\u0ec0\0\u0efb\0\u0f36\0\73\0\u0f71"+
    "\0\u0fac\0\u0fe7\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149"+
    "\0\u1184\0\261\0\u11bf\0\u11fa\0\u1235\0\u1270\0\u12ab\0\u12e6"+
    "\0\u1321\0\u135c\0\u1397\0\u13d2\0\u140d\0\u1448\0\u1483\0\u14be"+
    "\0\u14f9\0\u1534\0\u156f\0\u15aa\0\73\0\u15e5\0\u1620\0\u165b"+
    "\0\u1696\0\261\0\u16d1\0\u170c\0\261\0\u1747\0\u1782\0\261"+
    "\0\261\0\u17bd\0\261\0\u17f8\0\u1833\0\261\0\u186e\0\u18a9"+
    "\0\u18e4\0\u191f\0\u195a\0\u1448\0\u1448\0\u1995\0\u19d0\0\73"+
    "\0\u1a0b\0\73\0\u1a46\0\u1a81\0\u1abc\0\u1af7\0\261\0\261"+
    "\0\261\0\261\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3\0\u1c1e\0\261"+
    "\0\261\0\u1c59\0\u1c94\0\u1ccf\0\73\0\u1d0a\0\261\0\261"+
    "\0\u1d45\0\u1d80\0\261\0\261\0\261\0\u1dbb\0\u1df6\0\u1e31"+
    "\0\u1e6c\0\u1ea7\0\u1ee2\0\261\0\u1f1d\0\u1f58\0\u1f93\0\u1fce"+
    "\0\u2009\0\u2044\0\u207f\0\u20ba\0\u20f5\0\u2130\0\u216b\0\u21a6"+
    "\0\u21e1\0\u221c\0\u2257\0\261\0\u2292\0\u22cd\0\u2308\0\261"+
    "\0\u2343\0\73\0\261\0\261\0\u237e\0\u23b9\0\u23f4\0\261"+
    "\0\u242f\0\u246a\0\261\0\u24a5\0\u24e0\0\u251b\0\73";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\11\2\2\1\3\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\2\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\4\1\34"+
    "\1\4\1\35\1\36\1\37\1\40\1\41\2\4\1\42"+
    "\3\4\1\43\1\44\1\45\1\46\2\4\1\47\1\50"+
    "\1\51\1\52\3\2\74\0\2\3\11\0\1\3\61\0"+
    "\2\4\2\0\1\4\25\0\27\4\7\0\5\53\1\0"+
    "\1\54\64\53\6\0\1\55\30\0\1\56\1\57\2\0"+
    "\1\60\1\0\1\61\34\0\1\7\1\62\72\0\1\63"+
    "\62\0\11\64\1\65\1\66\60\64\12\67\1\70\2\67"+
    "\1\65\55\67\16\0\1\71\47\0\1\72\26\0\1\73"+
    "\2\0\1\74\42\0\1\75\1\76\1\77\24\0\1\100"+
    "\73\0\1\101\50\0\2\4\2\0\1\4\25\0\1\4"+
    "\1\102\25\4\12\0\2\4\2\0\1\4\25\0\5\4"+
    "\1\103\4\4\1\104\14\4\12\0\2\4\2\0\1\4"+
    "\25\0\3\4\1\105\10\4\1\106\12\4\12\0\2\4"+
    "\2\0\1\4\25\0\2\4\1\107\24\4\12\0\2\4"+
    "\2\0\1\4\25\0\17\4\1\110\7\4\12\0\2\4"+
    "\2\0\1\4\25\0\1\4\1\111\14\4\1\112\10\4"+
    "\12\0\2\4\2\0\1\4\25\0\20\4\1\113\6\4"+
    "\12\0\2\4\2\0\1\4\25\0\3\4\1\114\6\4"+
    "\1\115\14\4\12\0\2\4\2\0\1\4\25\0\1\4"+
    "\1\116\1\117\24\4\12\0\2\4\2\0\1\4\25\0"+
    "\1\120\26\4\12\0\2\4\2\0\1\4\25\0\7\4"+
    "\1\121\12\4\1\122\4\4\12\0\2\4\2\0\1\4"+
    "\25\0\2\4\1\123\24\4\12\0\2\4\2\0\1\4"+
    "\25\0\3\4\1\124\23\4\12\0\2\4\2\0\1\4"+
    "\25\0\5\4\1\125\21\4\76\0\1\126\3\0\5\53"+
    "\1\127\72\53\1\127\1\130\64\53\47\0\1\131\100\0"+
    "\1\132\77\0\1\133\66\0\1\134\23\0\1\62\63\0"+
    "\1\64\1\0\11\64\2\0\56\64\1\67\1\0\11\67"+
    "\2\0\56\67\1\71\1\0\71\71\16\135\1\0\47\135"+
    "\1\136\4\135\25\0\1\137\50\0\2\4\2\0\1\4"+
    "\25\0\2\4\1\140\3\4\1\141\20\4\12\0\2\4"+
    "\2\0\1\4\25\0\6\4\1\142\20\4\12\0\2\4"+
    "\2\0\1\4\25\0\10\4\1\143\16\4\12\0\2\4"+
    "\2\0\1\4\25\0\7\4\1\144\17\4\12\0\2\4"+
    "\2\0\1\4\25\0\6\4\1\145\3\4\1\146\14\4"+
    "\12\0\2\4\2\0\1\4\25\0\23\4\1\147\3\4"+
    "\12\0\2\4\2\0\1\4\25\0\1\150\1\151\25\4"+
    "\12\0\2\4\2\0\1\4\25\0\20\4\1\152\6\4"+
    "\12\0\2\4\2\0\1\4\25\0\12\4\1\153\14\4"+
    "\12\0\2\4\2\0\1\4\25\0\21\4\1\154\5\4"+
    "\12\0\2\4\2\0\1\4\25\0\6\4\1\155\20\4"+
    "\12\0\2\4\2\0\1\4\25\0\3\4\1\156\23\4"+
    "\12\0\2\4\2\0\1\4\25\0\7\4\1\157\17\4"+
    "\12\0\2\4\2\0\1\4\25\0\23\4\1\160\3\4"+
    "\12\0\2\4\2\0\1\4\25\0\3\4\1\161\23\4"+
    "\12\0\2\4\2\0\1\4\25\0\10\4\1\162\16\4"+
    "\12\0\2\4\2\0\1\4\25\0\23\4\1\163\3\4"+
    "\12\0\2\4\2\0\1\4\25\0\7\4\1\164\17\4"+
    "\12\0\2\4\2\0\1\4\25\0\2\4\1\165\24\4"+
    "\7\0\5\130\1\166\65\130\51\0\1\167\65\0\1\170"+
    "\100\0\1\171\66\0\1\172\24\0\16\135\1\0\47\135"+
    "\1\173\4\135\16\174\1\175\47\174\1\176\4\174\3\0"+
    "\2\4\2\0\1\4\25\0\3\4\1\177\23\4\12\0"+
    "\2\4\2\0\1\4\25\0\16\4\1\200\10\4\12\0"+
    "\2\4\2\0\1\4\25\0\1\4\1\201\25\4\12\0"+
    "\2\4\2\0\1\4\25\0\1\4\1\202\25\4\12\0"+
    "\2\4\2\0\1\4\25\0\10\4\1\203\16\4\12\0"+
    "\2\4\2\0\1\4\25\0\2\4\1\204\24\4\12\0"+
    "\2\4\2\0\1\4\25\0\12\4\1\205\14\4\12\0"+
    "\2\4\2\0\1\4\25\0\15\4\1\206\11\4\12\0"+
    "\2\4\2\0\1\4\25\0\3\4\1\207\23\4\12\0"+
    "\2\4\2\0\1\4\25\0\7\4\1\210\17\4\12\0"+
    "\2\4\2\0\1\4\25\0\12\4\1\211\14\4\12\0"+
    "\2\4\2\0\1\4\25\0\6\4\1\212\20\4\12\0"+
    "\2\4\2\0\1\4\25\0\3\4\1\213\23\4\12\0"+
    "\2\4\2\0\1\4\25\0\13\4\1\214\13\4\12\0"+
    "\2\4\2\0\1\4\25\0\11\4\1\215\15\4\12\0"+
    "\2\4\2\0\1\4\25\0\15\4\1\216\11\4\12\0"+
    "\2\4\2\0\1\4\25\0\2\4\1\217\24\4\12\0"+
    "\2\4\2\0\1\4\25\0\6\4\1\220\20\4\12\0"+
    "\2\4\2\0\1\4\25\0\15\4\1\221\11\4\12\0"+
    "\2\4\2\0\1\4\25\0\21\4\1\222\5\4\12\0"+
    "\2\4\2\0\1\4\25\0\1\4\1\223\25\4\7\0"+
    "\5\224\1\225\65\224\45\0\1\226\63\0\1\227\72\0"+
    "\1\230\100\0\1\231\26\0\16\135\1\175\47\135\1\173"+
    "\4\135\16\174\1\0\47\174\1\176\22\174\1\232\47\174"+
    "\1\176\4\174\3\0\2\4\2\0\1\4\25\0\1\233"+
    "\26\4\12\0\2\4\2\0\1\4\25\0\1\234\26\4"+
    "\12\0\2\4\2\0\1\4\25\0\7\4\1\235\17\4"+
    "\12\0\2\4\2\0\1\4\25\0\6\4\1\236\20\4"+
    "\12\0\2\4\2\0\1\4\25\0\17\4\1\237\7\4"+
    "\12\0\2\4\2\0\1\4\25\0\11\4\1\240\1\241"+
    "\14\4\12\0\2\4\2\0\1\4\25\0\20\4\1\242"+
    "\6\4\12\0\2\4\2\0\1\4\25\0\2\4\1\243"+
    "\24\4\12\0\2\4\2\0\1\4\25\0\14\4\1\244"+
    "\12\4\12\0\2\4\2\0\1\4\25\0\6\4\1\245"+
    "\20\4\12\0\2\4\2\0\1\4\25\0\1\4\1\246"+
    "\25\4\12\0\2\4\2\0\1\4\25\0\14\4\1\247"+
    "\12\4\12\0\2\4\2\0\1\4\25\0\11\4\1\250"+
    "\1\251\14\4\12\0\2\4\2\0\1\4\25\0\6\4"+
    "\1\252\20\4\12\0\2\4\2\0\1\4\25\0\15\4"+
    "\1\253\11\4\54\0\1\254\62\0\1\255\106\0\1\256"+
    "\24\0\2\4\2\0\1\4\25\0\4\4\1\257\22\4"+
    "\12\0\2\4\2\0\1\4\25\0\7\4\1\260\17\4"+
    "\12\0\2\4\2\0\1\4\25\0\4\4\1\261\22\4"+
    "\12\0\2\4\2\0\1\4\25\0\2\4\1\262\24\4"+
    "\12\0\2\4\2\0\1\4\25\0\17\4\1\263\7\4"+
    "\12\0\2\4\2\0\1\4\25\0\12\4\1\264\14\4"+
    "\12\0\2\4\2\0\1\4\25\0\17\4\1\265\7\4"+
    "\12\0\2\4\2\0\1\4\25\0\4\4\1\266\22\4"+
    "\12\0\2\4\2\0\1\4\25\0\7\4\1\267\17\4"+
    "\12\0\2\4\2\0\1\4\25\0\3\4\1\270\23\4"+
    "\12\0\2\4\2\0\1\4\25\0\6\4\1\271\20\4"+
    "\72\0\1\272\52\0\1\273\32\0\2\4\2\0\1\4"+
    "\25\0\10\4\1\274\16\4\12\0\2\4\2\0\1\4"+
    "\25\0\12\4\1\275\14\4\12\0\2\4\2\0\1\4"+
    "\25\0\16\4\1\276\10\4\12\0\2\4\2\0\1\4"+
    "\25\0\2\4\1\277\24\4\12\0\2\4\2\0\1\4"+
    "\25\0\1\300\26\4\12\0\2\4\2\0\1\4\25\0"+
    "\21\4\1\301\5\4\45\0\1\302\107\0\1\303\22\0"+
    "\2\4\2\0\1\4\25\0\14\4\1\304\12\4\12\0"+
    "\2\4\2\0\1\4\25\0\1\305\26\4\12\0\2\4"+
    "\2\0\1\4\25\0\1\4\1\306\25\4\12\0\2\4"+
    "\2\0\1\4\25\0\1\4\1\307\25\4\12\0\2\4"+
    "\2\0\1\4\25\0\3\4\1\310\23\4\54\0\1\311"+
    "\62\0\1\312\40\0\2\4\2\0\1\4\25\0\10\4"+
    "\1\313\16\4\12\0\2\4\2\0\1\4\25\0\1\4"+
    "\1\314\25\4\12\0\2\4\2\0\1\4\25\0\3\4"+
    "\1\315\23\4\12\0\2\4\2\0\1\4\25\0\5\4"+
    "\1\316\1\4\1\317\17\4\12\0\2\4\2\0\1\4"+
    "\25\0\7\4\1\320\17\4\46\0\1\321\71\0\1\322"+
    "\37\0\2\4\2\0\1\4\25\0\10\4\1\323\16\4"+
    "\12\0\2\4\2\0\1\4\25\0\22\4\1\324\4\4"+
    "\12\0\2\4\2\0\1\4\25\0\21\4\1\325\5\4"+
    "\12\0\2\4\2\0\1\4\25\0\6\4\1\326\20\4"+
    "\44\0\1\327\40\0\2\4\2\0\1\4\25\0\6\4"+
    "\1\330\20\4\12\0\2\4\2\0\1\4\25\0\1\4"+
    "\1\331\25\4\65\0\1\332\17\0\2\4\2\0\1\4"+
    "\25\0\1\333\26\4\61\0\1\334\63\0\1\335\67\0"+
    "\1\336\67\0\1\337\35\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9558];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\11\1\2\11\1\1\1\11\2\1\7\11"+
    "\16\1\3\11\1\1\2\0\1\11\4\0\1\1\1\11"+
    "\1\0\1\11\3\0\1\1\1\0\1\11\1\1\5\11"+
    "\24\1\2\11\7\0\1\11\27\1\6\0\1\11\1\0"+
    "\25\1\1\0\1\1\2\0\1\11\1\0\1\11\21\1"+
    "\1\0\1\11\1\0\13\1\2\0\6\1\2\0\5\1"+
    "\2\0\6\1\1\0\1\11\4\1\1\0\2\1\1\0"+
    "\1\1\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _JawaLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _JawaLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return com.intellij.psi.TokenType.BAD_CHARACTER;
            }
          case 69: break;
          case 2: 
            { return com.intellij.psi.TokenType.WHITE_SPACE;
            }
          case 70: break;
          case 3: 
            { return ID;
            }
          case 71: break;
          case 4: 
            { return AT;
            }
          case 72: break;
          case 5: 
            { return NUMBER;
            }
          case 73: break;
          case 6: 
            { return DOT;
            }
          case 74: break;
          case 7: 
            { return DIV;
            }
          case 75: break;
          case 8: 
            { return SEMI;
            }
          case 76: break;
          case 9: 
            { return COMMA;
            }
          case 77: break;
          case 10: 
            { return HAT;
            }
          case 78: break;
          case 11: 
            { return BAR;
            }
          case 79: break;
          case 12: 
            { return POUND;
            }
          case 80: break;
          case 13: 
            { return LBRACE;
            }
          case 81: break;
          case 14: 
            { return RBRACE;
            }
          case 82: break;
          case 15: 
            { return LBRACKET;
            }
          case 83: break;
          case 16: 
            { return RBRACKET;
            }
          case 84: break;
          case 17: 
            { return LPAREN;
            }
          case 85: break;
          case 18: 
            { return RPAREN;
            }
          case 86: break;
          case 19: 
            { return ADD;
            }
          case 87: break;
          case 20: 
            { return SUB;
            }
          case 88: break;
          case 21: 
            { return MUL;
            }
          case 89: break;
          case 22: 
            { return STATIC_PREFIX;
            }
          case 90: break;
          case 23: 
            { return RANGE;
            }
          case 91: break;
          case 24: 
            { return STRING_LITERAL;
            }
          case 92: break;
          case 25: 
            { return JawaTokenTypes.LINE_COMMENT();
            }
          case 93: break;
          case 26: 
            { return OR;
            }
          case 94: break;
          case 27: 
            { return SHR;
            }
          case 95: break;
          case 28: 
            { return AND;
            }
          case 96: break;
          case 29: 
            { return XOR;
            }
          case 97: break;
          case 30: 
            { return SHL;
            }
          case 98: break;
          case 31: 
            { return ASSIGN_OP;
            }
          case 99: break;
          case 32: 
            { return ARROW;
            }
          case 100: break;
          case 33: 
            { return IF;
            }
          case 101: break;
          case 34: 
            { return REM;
            }
          case 102: break;
          case 35: 
            { return APOSTROPHE_ID;
            }
          case 103: break;
          case 36: 
            { return USHR;
            }
          case 104: break;
          case 37: 
            { return NEW;
            }
          case 105: break;
          case 38: 
            { //for comments in interpolated strings
    return JawaTokenTypes.BLOCK_COMMENT();
            }
          case 106: break;
          case 39: 
            { return ELSE;
            }
          case 107: break;
          case 40: 
            { return CALL;
            }
          case 108: break;
          case 41: 
            { return THEN;
            }
          case 109: break;
          case 42: 
            { return NULL_LITERAL;
            }
          case 110: break;
          case 43: 
            { return GOTO;
            }
          case 111: break;
          case 44: 
            { return LCMP;
            }
          case 112: break;
          case 45: 
            { return STATIC_ID;
            }
          case 113: break;
          case 46: 
            { return TYPE_KEY;
            }
          case 114: break;
          case 47: 
            { //for comments in interpolated strings
    return JawaTokenTypes.DOC_COMMENT();
            }
          case 115: break;
          case 48: 
            { return CATCH;
            }
          case 116: break;
          case 49: 
            { return DCMPG;
            }
          case 117: break;
          case 50: 
            { return DCMPL;
            }
          case 118: break;
          case 51: 
            { return THROW;
            }
          case 119: break;
          case 52: 
            { return FCMPG;
            }
          case 120: break;
          case 53: 
            { return FCMPL;
            }
          case 121: break;
          case 54: 
            { return OWNER_KEY;
            }
          case 122: break;
          case 55: 
            { return CLASS_OR_INTERFACE;
            }
          case 123: break;
          case 56: 
            { return RETURN;
            }
          case 124: break;
          case 57: 
            { return SWITCH;
            }
          case 125: break;
          case 58: 
            { return STATIC_FIELD;
            }
          case 126: break;
          case 59: 
            { return LENGTH;
            }
          case 127: break;
          case 60: 
            { return EXTENDS_AND_IMPLEMENTS;
            }
          case 128: break;
          case 61: 
            { return METHOD;
            }
          case 129: break;
          case 62: 
            { return EXCEPTION;
            }
          case 130: break;
          case 63: 
            { return SIGNATURE_KEY;
            }
          case 131: break;
          case 64: 
            { return CONST_CLASS;
            }
          case 132: break;
          case 65: 
            { return INSTANCEOF;
            }
          case 133: break;
          case 66: 
            { return MONITOR_EXIT;
            }
          case 134: break;
          case 67: 
            { return MONITOR_ENTER;
            }
          case 135: break;
          case 68: 
            { return CLASS_DESCRIPTOR_KEY;
            }
          case 136: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
